#!/bin/bash
echo -e "Best School" > \\\*\\\\"'\"Best School\"\\'"\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\) 
#"corect text" \\\*\\\\"'\"Holberton School\"\\'"\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)
#OG output \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
